In [112]:
import pandas as pd
import matplotlib
from sklearn.model_selection import train_test_split

In [113]:
df = pd.read_csv("train.csv")
df.dropna(subset=["SalePrice"], axis=0, inplace=True)
df.sample(frac=1)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1020,1021,20,RL,60.0,7024,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,176000
241,242,30,RM,40.0,3880,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,110500
1245,1246,80,RL,78.0,12090,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2007,WD,Abnorml,178000
23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
1367,1368,160,RM,41.0,2665,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,127000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,342,20,RH,60.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,82000
406,407,50,RL,51.0,10480,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2008,WD,Normal,115000
670,671,60,RL,64.0,8633,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2009,WD,Normal,173500
680,681,120,RL,50.0,8012,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,143000
1317,1318,120,FV,47.0,4230,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2007,New,Partial,208900

In [114]:
y = df['SalePrice']

In [115]:
x = df.drop(['SalePrice'], axis=1)

In [116]:
X_train, X_validate, y_train, y_validate = train_test_split(x,y, train_size=0.8, test_size=0.2, shuffle=False)

In [117]:
cat_train = [col for col in X_train if X_train[col].nunique() < 8 and X_train[col].dtype == 'object']
cat_train

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition2',
 'BldgType',
 'RoofStyle',
 'RoofMatl',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleCondition']

In [118]:
#cat_validate = [col for col in X_validate if X_validate[col].nunique() < 10 and X_validate[col].dtype == 'object']
#cat_validate

In [119]:
num_train = [col for col in X_train if  X_train[col].dtype in ['int64', 'float64']] 
num_train

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [120]:
#num_validate = [col for col in X_validate if X_validate[col].dtype in ['int64', 'float64']] 
#num_validate

In [121]:
my_cols_train = num_train + cat_train
#my_cols_validate = num_validate + cat_validate

X_train = X_train[my_cols_train]
X_validate = X_validate[my_cols_train]

In [122]:
X_train

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleCondition
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,NaN,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,Normal
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,Normal
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,Normal
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,Gd,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,Abnorml
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,1164,90,60.0,12900,4,4,1969,1969,0.0,1198,...,NaN,CarPort,Unf,Fa,TA,Y,NaN,NaN,NaN,Alloca
1164,1165,80,NaN,16157,5,7,1978,1978,0.0,680,...,TA,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,Normal
1165,1166,20,79.0,9541,7,5,2009,2009,268.0,0,...,NaN,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,Partial
1166,1167,20,64.0,10475,8,5,2008,2008,72.0,0,...,NaN,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,Normal
1167,1168,60,58.0,10852,6,5,2000,2000,0.0,786,...,TA,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,Normal

In [123]:
X_train_copy = X_train.copy()
X_validate_copy = X_validate.copy()

In [124]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy='median')

# Preprocessing for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent'))
])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, num_train),
        ('cat', categorical_transformer, cat_train)
    ])

In [125]:
X_train = pd.DataFrame(preprocessor.fit_transform(X_train))
X_validate = pd.DataFrame(preprocessor.transform(X_validate))

In [126]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,64,65,66,67,68,69,70,71,72,73
0,1,60,65,8450,7,5,2003,2003,196,706,...,Gd,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,Normal
1,2,20,80,9600,6,8,1976,1976,0,978,...,TA,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,Normal
2,3,60,68,11250,7,5,2001,2002,162,486,...,TA,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,Normal
3,4,70,60,9550,7,5,1915,1970,0,216,...,Gd,Detchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,Abnorml
4,5,60,84,14260,8,5,2000,2000,350,655,...,TA,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,1164,90,60,12900,4,4,1969,1969,0,1198,...,Gd,CarPort,Unf,Fa,TA,Y,Ex,MnPrv,Shed,Alloca
1164,1165,80,70,16157,5,7,1978,1978,0,680,...,TA,Attchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,Normal
1165,1166,20,79,9541,7,5,2009,2009,268,0,...,Gd,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,Partial
1166,1167,20,64,10475,8,5,2008,2008,72,0,...,Gd,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,Normal
1167,1168,60,58,10852,6,5,2000,2000,0,786,...,TA,Attchd,Fin,TA,TA,Y,Ex,MnPrv,Shed,Normal

In [127]:
X_train.columns = X_train_copy.columns
X_validate.columns = X_validate_copy.columns

In [128]:
good_label_cols = [col for col in cat_train if 
                   set(X_train[col]) == set(X_validate[col])]

# set(x_train["NombreDeColumna"]) te da los distintos valores de esa columna
        
# Problematic columns that will be dropped from the dataset
bad_label_cols = list(set(cat_train)-set(good_label_cols))

In [129]:
set(good_label_cols)

{'Alley',
 'BldgType',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'BsmtQual',
 'CentralAir',
 'ExterQual',
 'Fence',
 'FireplaceQu',
 'Foundation',
 'GarageFinish',
 'GarageType',
 'KitchenQual',
 'LandContour',
 'LandSlope',
 'LotConfig',
 'LotShape',
 'MSZoning',
 'MasVnrType',
 'PavedDrive',
 'Street'}

In [130]:
X_train = X_train.drop(bad_label_cols, axis=1)
X_validate = X_validate.drop(bad_label_cols, axis=1)

In [131]:
# Apply label encoder

label_encoder = LabelEncoder()

for col in set(good_label_cols):
    
    X_train[col] = label_encoder.fit_transform(X_train[col])
    X_validate[col] = label_encoder.transform(X_validate[col])

In [132]:
X_train

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,BsmtExposure,BsmtFinType1,BsmtFinType2,CentralAir,KitchenQual,FireplaceQu,GarageType,GarageFinish,PavedDrive,Fence
0,1,60,65,8450,7,5,2003,2003,196,706,...,3,2,5,1,2,2,1,1,2,2
1,2,20,80,9600,6,8,1976,1976,0,978,...,1,0,5,1,3,4,1,1,2,2
2,3,60,68,11250,7,5,2001,2002,162,486,...,2,2,5,1,2,4,1,1,2,2
3,4,70,60,9550,7,5,1915,1970,0,216,...,3,0,5,1,2,2,5,2,2,2
4,5,60,84,14260,8,5,2000,2000,350,655,...,0,2,5,1,2,4,1,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,1164,90,60,12900,4,4,1969,1969,0,1198,...,0,2,5,1,3,2,4,2,2,2
1164,1165,80,70,16157,5,7,1978,1978,0,680,...,1,0,4,1,2,4,1,2,2,2
1165,1166,20,79,9541,7,5,2009,2009,268,0,...,3,5,5,1,2,2,1,1,2,2
1166,1167,20,64,10475,8,5,2008,2008,72,0,...,0,5,5,1,2,2,1,1,2,2
1167,1168,60,58,10852,6,5,2000,2000,0,786,...,3,2,5,1,3,4,1,0,2,2

In [133]:
#X_train = X_train[['OverallQual', 'TotalBsmtSF']]
#X_validate = X_validate[['OverallQual', 'TotalBsmtSF']]

In [141]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

for k in [3]:
    
    neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train, y_train)
    predicciones = neigh.predict(X_validate)
    
    print("Test set Accuracy: ", metrics.accuracy_score(y_validate, predicciones))
    print("MAE: ", mean_absolute_error(y_validate, predicciones))

Test set Accuracy:  0.0136986301369863
MAE:  46193.32191780822

In [135]:
X_validate

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,BsmtExposure,BsmtFinType1,BsmtFinType2,CentralAir,KitchenQual,FireplaceQu,GarageType,GarageFinish,PavedDrive,Fence
0,1169,70,120,13728,6,7,1935,1986,0,626,...,3,4,5,1,2,4,2,2,2,2
1,1170,60,118,35760,10,5,1995,1996,1378,1387,...,1,2,5,1,2,4,1,0,2,2
2,1171,80,76,9880,6,6,1977,1977,0,522,...,0,0,5,1,3,3,1,0,2,0
3,1172,20,76,9120,6,6,1958,1958,0,662,...,3,0,5,1,3,4,1,1,2,2
4,1173,160,35,4017,7,5,2006,2007,0,0,...,3,5,5,1,2,2,5,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,1456,60,62,7917,6,5,1999,2000,0,0,...,3,5,5,1,3,4,1,1,2,2
288,1457,20,85,13175,6,6,1978,1988,119,790,...,3,0,4,1,3,4,1,2,2,2
289,1458,70,66,9042,7,9,1941,2006,0,275,...,3,2,5,1,2,2,1,1,2,0
290,1459,20,68,9717,5,6,1950,1996,0,49,...,2,2,4,1,2,2,1,2,2,2
291,1460,20,75,9937,5,6,1965,1965,0,830,...,3,1,3,1,3,2,1,0,2,2

In [136]:
X_train

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,BsmtExposure,BsmtFinType1,BsmtFinType2,CentralAir,KitchenQual,FireplaceQu,GarageType,GarageFinish,PavedDrive,Fence
0,1,60,65,8450,7,5,2003,2003,196,706,...,3,2,5,1,2,2,1,1,2,2
1,2,20,80,9600,6,8,1976,1976,0,978,...,1,0,5,1,3,4,1,1,2,2
2,3,60,68,11250,7,5,2001,2002,162,486,...,2,2,5,1,2,4,1,1,2,2
3,4,70,60,9550,7,5,1915,1970,0,216,...,3,0,5,1,2,2,5,2,2,2
4,5,60,84,14260,8,5,2000,2000,350,655,...,0,2,5,1,2,4,1,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,1164,90,60,12900,4,4,1969,1969,0,1198,...,0,2,5,1,3,2,4,2,2,2
1164,1165,80,70,16157,5,7,1978,1978,0,680,...,1,0,4,1,2,4,1,2,2,2
1165,1166,20,79,9541,7,5,2009,2009,268,0,...,3,5,5,1,2,2,1,1,2,2
1166,1167,20,64,10475,8,5,2008,2008,72,0,...,0,5,5,1,2,2,1,1,2,2
1167,1168,60,58,10852,6,5,2000,2000,0,786,...,3,2,5,1,3,4,1,0,2,2

In [137]:
import matplotlib

In [138]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

for k in range(1,10):
    
    neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
    predicciones = neigh.predict(X_validate)
    
    print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
    print("Test set Accuracy: ", metrics.accuracy_score(y_validate, predicciones))

Train set Accuracy:  1.0
Test set Accuracy:  0.003424657534246575
Train set Accuracy:  0.5102739726027398
Test set Accuracy:  0.00684931506849315
Train set Accuracy:  0.3287671232876712
Test set Accuracy:  0.0136986301369863
Train set Accuracy:  0.2525684931506849
Test set Accuracy:  0.00684931506849315
Train set Accuracy:  0.1892123287671233
Test set Accuracy:  0.003424657534246575
Train set Accuracy:  0.1523972602739726
Test set Accuracy:  0.003424657534246575
Train set Accuracy:  0.1292808219178082
Test set Accuracy:  0.003424657534246575
Train set Accuracy:  0.1232876712328767
Test set Accuracy:  0.0
Train set Accuracy:  0.1172945205479452
Test set Accuracy:  0.0